sudo: required
services:
  - docker

before_install:
  - docker build -t amanindra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amanindra/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-864517445533"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"